import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, Filter, MapPin, Search, SlidersHorizontal, Star, UsersRound } from "lucide-react";
import { PortalShell } from "./portal-shell";

const cases = [
  { title: "Orientación por accidente de tránsito", category: "Derecho Penal", location: "Concepción", mode: "Atención remota", credit: "5 créditos", time: "Hace 2 horas" },
  { title: "Consulta por despido injustificado", category: "Derecho Laboral", location: "Región Metropolitana", mode: "Online o presencial", credit: "7 créditos", time: "Hace 5 horas" },
  { title: "Representación en causa penal", category: "Derecho Penal", location: "Biobío", mode: "Atención presencial", credit: "9 créditos", time: "Ayer" },
];

function CaseCard({ item, accessed = false }: { item: typeof cases[number]; accessed?: boolean }) { return <article className="case-list-card"><div className="case-card-top"><span className="case-category">{item.category}</span><span className={accessed ? "state-chip active" : "credit-chip"}>{accessed ? "Contactado" : item.credit}</span></div><h2>{item.title}</h2><p><MapPin size={15} /> {item.location} <span>·</span> {item.mode}</p><footer><span><Clock3 size={14} /> {item.time}</span><button className="portal-outline-button">{accessed ? "Ver seguimiento" : "Ver detalle"} <ArrowRight size={15} /></button></footer></article>; }

export function PoolCasesPage() { return <PortalShell><div className="portal-page-heading"><div><p className="eyebrow">Oportunidades disponibles</p><h1>Casos del pool</h1><p>Explora oportunidades abiertas y filtra por tus áreas de interés.</p></div><button className="portal-outline-button"><SlidersHorizontal size={17} /> Ajustar filtros</button></div><section className="case-toolbar"><label><Search size={17} /><input placeholder="Buscar por especialidad o región" /></label><button><Filter size={16} /> Todos los casos</button><span>3 oportunidades disponibles</span></section><div className="case-list-grid">{cases.map((item) => <CaseCard item={item} key={item.title} />)}</div></PortalShell>; }

export function PreferredCasesPage() { return <PortalShell><div className="portal-page-heading"><div><p className="eyebrow">Oportunidades seleccionadas</p><h1>Casos preferentes</h1><p>Cuando exista una coincidencia de alto potencial, aparecerá aquí primero.</p></div></div><section className="portal-panel preferred-empty"><span className="empty-mark"><Star size={29} /></span><p className="eyebrow">Aún no hay coincidencias</p><h2>Estamos buscando el caso adecuado para tu práctica.</h2><p>Mientras tanto, revisa el pool de oportunidades o mejora los filtros de tu perfil para afinar las próximas coincidencias.</p><div><Link className="portal-primary-button" href="/casos/pool">Explorar casos del pool <ArrowRight size={17} /></Link><Link className="portal-outline-button" href="/account">Actualizar mi perfil</Link></div></section><section className="tips-grid"><article><span><UsersRound size={19} /></span><h2>Más oportunidades</h2><p>Explora casos abiertos que aún no han sido asignados.</p><Link href="/casos/pool">Ver pool <ArrowRight size={14} /></Link></article><article><span><CheckCircle2 size={19} /></span><h2>Perfil más preciso</h2><p>Revisa especialidades, ubicación y modalidad de atención.</p><Link href="/account">Editar perfil <ArrowRight size={14} /></Link></article></section></PortalShell>; }

export function AccessedCasesPage() { return <PortalShell><div className="portal-page-heading"><div><p className="eyebrow">Historial profesional</p><h1>Casos accedidos</h1><p>Revisa tus oportunidades contactadas y mantiene el seguimiento al día.</p></div></div><section className="case-toolbar"><label><Search size={17} /><input placeholder="Buscar en tu historial" /></label><button><Filter size={16} /> Todos los estados</button><span>2 casos en seguimiento</span></section><div className="case-list-grid">{cases.slice(0, 2).map((item) => <CaseCard item={item} accessed key={item.title} />)}</div></PortalShell>; }
